server:
  port: 8080
  servlet:
    context-path: /api
spring:
  config:
    name: application.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/DEMO_WEB
    username: root
    password: nhatcoi2004
    hikari:
      maximum-pool-size: 8
    driver-class-name: com.mysql.jdbc.Driver

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

